locale: en-US
title: Fauzan Alfi
name: Fauzan Alfi
description: BIM Engineer. XR Designer.
url: https://fauzanalfi.github.io
baseurl: ""
repository: fauzanalfi/fauzanalfi.github.io
timezone: Asia/Jakarta
future: false
remote_theme: academicpages/academicpages.github.io
site_theme: default
collections:
  research_projects:
    output: true
    permalink: /research/:title/
author:
  github: fauzanalfi
  bio: BIM Engineer. XR Designer.
  name: Fauzan
  instagram: fauzanalfi
  twitter: fauzanalfi
  location: Indonesia
  avatar: ""
  email: hi@fauzan.id
  linkedin: fauzanalfi
  cv_url: ""
comments:
  provider: disqus
  disqus:
    shortname: fauzanalfi
breadcrumbs: false
read_more: disabled
permalink: /posts/:title/
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate
  - jekyll-redirect-from
  - jemoji
  - jekyll-include-cache
  - jekyll-remote-theme
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      featured: false
      sort_order: 999
  - scope:
      path: ""
      type: pages
    values:
      layout: page
      author_profile: false
  - scope:
      path: ""
      type: research_projects
    values:
      layout: research_project
      featured: false
      sort_order: 999
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
include:
  - _pages
  - robots.txt
