title: Fauzan @ GitHub
author: Fauzan
email: hi@fauzan.id
description: > # this means to ignore newlines until "show_exerpts:"
  Just another weblog. But on GitHub.
show_excerpts: true # set to true to show excerpts on the homepage
baseurl: ''

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Fauzan @ GitHub
  tagline: BIM Engineer. XR Designer.
  date_format: "%b %-d, %Y"
  style: blue
  showNav: true
  showPicker: false
  disqus_shortname: fauzanalfi
  navigation:
    - title: About
      url: "/about"
    - title: Project
      url: "/project"

  # generate social links in footer
  social_links:
    twitter: fauzanalfi
    github:  fauzanalfi
    linkedIn: in/fauzanalfi
    instagram: fauzanalfi
    rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: texture

plugins:
  - jekyll-seo-tag
  - jekyll-feed