locale: en-US
title: Fauzan Alfi
name: Fauzan Alfi
description: Lecturer @ ITB. Certified BIM Manager
url: https://fauzanalfi.github.io
baseurl: ""
repository: fauzanalfi/fauzanalfi.github.io
timezone: Asia/Jakarta
future: false
remote_theme: academicpages/academicpages.github.io
site_theme: default
author:
  cv_url: ""
  github: fauzanalfi
  bio: Lecturer @ ITB. Certified BIM Manager
  name: Fauzan Alfi
  instagram: fauzanalfi
  twitter: fauzanalfi
  location: Indonesia
  avatar: https://scontent.fbdo7-1.fna.fbcdn.net/v/t39.30808-6/515513780_10162745596393544_8496920479865372743_n.jpg?_nc_cat=111&ccb=1-7&_nc_sid=53a332&_nc_eui2=AeEdijYpA_tSM63rgN6IA39uUy8fUaJRzuZTLx9RolHO5lI_itThCU4q0MvuqiC2zHU&_nc_ohc=UCU35jPkPGgQ7kNvwFUKYjX&_nc_oc=AdquOmmNxsYFh5kURg2sGq0UmbPWe3ar2d4iKjggV1PnS9oRoSC3AZOlrNZS-EjM9zZHQbkzDzVpU3crVuh3Ulxo&_nc_zt=23&_nc_ht=scontent.fbdo7-1.fna&_nc_gid=D4Ke_D5NoxDpn71pO3g4fw&_nc_ss=7a30f&oh=00_Afy6xDQKeWPsh-u3g5eGWtBRDkned6QT7bJc74P9KJOLpA&oe=69C2ACA9
  email: hi@fauzan.id
  linkedin: fauzanalfi
comments:
  provider: disqus
  disqus:
    shortname: fauzanalfi
breadcrumbs: false
read_more: disabled
permalink: /posts/:title/
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate
  - jekyll-redirect-from
  - jemoji
  - jekyll-include-cache
  - jekyll-remote-theme
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      featured: false
      sort_order: 999
  - scope:
      path: ""
      type: pages
    values:
      layout: page
      author_profile: false
  - scope:
      path: ""
      type: research_projects
    values:
      layout: research_project
      featured: false
      sort_order: 999
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
include:
  - _pages
  - robots.txt
collections:
  research_projects:
    output: true
    permalink: /research/:title/
